#!/usr/bin/env python3
"""`C1-T6` — refuse a register ID in a commit subject.

The two-tier ID grammar (`turing-review:D14`). **Structural IDs appear in git;
register IDs never do.** `C1`, `F1`, `F1-T2`, `F4c` belong in a commit subject.
`D5`, `RR8`, `O11`, `H3`, `M1`, `FR17`, `NFR7` do not — the task that builds or
closes a register item carries the `F`/`C` ID, and the register item is explained in
the commit *body*, where it is correct usage.

**Only the first line is constrained.** A register ID in the body is the right way to
say why a change was made.

    python scripts/check_commit_msg.py .git/COMMIT_EDITMSG
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REGISTER_ID = re.compile(r"\b(?:NFR|FR|RR|[DOHMG])\d{1,3}\b")

# The retrofit letter belongs to the FEATURE, so it comes before the task: `F4c-T1`
# is a task of retrofit `F4c`. The letter was previously placed after `-T`, which
# made a retrofit that has tasks impossible to commit.
CONVENTIONAL = re.compile(r"^(?:feat|fix|test|chore|docs|refactor|ci)"
                          r"\((?:[FC]\d{1,3}[a-z]?(?:-T\d{1,3})?)\): .+")

# `git revert` and `git merge` generate these, and refusing them means the hook has
# to be bypassed for an ordinary operation — which is how a gate gets deleted.
GENERATED = re.compile(r'^(?:Revert ".*"|Merge (?:branch|pull request|remote-tracking) .*)$')

# Accepted false positives, recorded rather than fixed: `H264`, `O365` and friends
# match the register-ID shape and nothing in a subject line distinguishes them from a
# real citation. Named here so the next person reads a decision instead of a bug.


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        raise SystemExit("usage: check_commit_msg.py <path to commit message>")

    lines = Path(argv[1]).read_text(encoding="utf-8").splitlines()
    subject = next((l for l in lines if l.strip() and not l.startswith("#")), "")

    if not subject:
        print("\ncommit-msg: REFUSED — the message has no subject line.\n", file=sys.stderr)
        return 1

    if GENERATED.match(subject):
        print("commit-msg: pass (generated by git)")
        return 0

    problems: list[str] = []

    for m in REGISTER_ID.finditer(subject):
        problems.append(
            f"  `{m.group()}` is a register ID and must not appear in a subject line.\n"
            f"      Cite the F/C task that builds or closes it in the scope, and explain\n"
            f"      it in the body — a register ID in the body is correct usage.")

    if not CONVENTIONAL.match(subject):
        problems.append(
            "  the subject is not `<type>(<ID>): <description>`.\n"
            "      Types: feat fix test chore docs refactor ci.\n"
            "      The ID in the scope is structural: C1, F1, F1-T2, F4c.\n"
            f"      Got: {subject!r}")

    if not problems:
        print("commit-msg: pass")
        return 0

    print("\ncommit-msg: REFUSED\n", file=sys.stderr)
    for p in problems:
        print(p, file=sys.stderr)
    print("", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
